sudo: required
dist: trusty
group: edge
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # Repo for Yarn
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH="$HOME/.yarn/bin:$PATH"

language: node_js
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome
# setting up Chrome for e2e tests
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default

# Building for a specific set of node versions
node_js:
  - '8'

# the following step should start the virtual X frame buffer: Xvfb process
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #wait a while before xvfb to start
after_script:
  - "sh -e /etc/init.d/xvfb stop"
